version: "3.2"

services:
  # syslog
  rsyslog:
    image: rsyslog/syslog_appliance_alpine
    container_name: rsyslog
    platform: linux/amd64
    volumes:
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf:ro
    networks:
      backend:
        ipv4_address: 172.28.1.3

  # HAProxy ingress router
  haproxy:
    image: haproxy:1.5.18
    container_name: haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    platform: linux/amd64
    networks:
      backend:
        ipv4_address: 172.28.1.4

  # Zeus traffic manager
  zeus:
    build:
      context: ./zeus
    container_name: zeus
    platform: linux/amd64
    environment:
      - ZEUS_EULA=accept
      - ZEUS_PASS=admin
    privileged: true
    init: true
    tty: true
    ports:
      - "8080:8080"
      - "9070:9070"
      - "9080:9080"
      - "9090:9090"
    networks:
      backend:
        ipv4_address: 172.28.1.5

  # websocket
  web:
    build:
      context: ./web
    container_name: websocket
    platform: linux/amd64
    networks:
      backend:
        ipv4_address: 172.28.1.6

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
